[package]
name = "wedding-backend"
version = "0.1.1"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.2.0", features = ["postgres"]  }
dotenvy = "0.15"
